import type { Metadata } from "next";
import { Theme } from '@radix-ui/themes';
import { Inter } from "next/font/google";
import '@radix-ui/themes/styles.css';
import "./globals.css";
import Navbar from "@/components/navbar";
import ContextProvider from "@/context/GlobalContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ContextProvider>
          <Theme appearance="dark">
            <Navbar />
            {children}
          </Theme>
        </ContextProvider>
      </body>
    </html >
  );
}
